/*CRIA BANCO LIVRARIA*/
CREATE DATABASE LIVRARIA
GO

/*CONECTA AO BANCO*/
USE LIVRARIA
GO

/*CRIAR TABELA ENDEREÇO */
CREATE TABLE ENDERECO(
	ID_ENDERECO INT IDENTITY,
	RUA VARCHAR(200) NOT NULL,
	NUMERO INT NOT NULL CHECK(NUMERO > 0),
	BAIRRO VARCHAR(150) NOT NULL,
	CIDADE VARCHAR(150) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	COMPLEMENTO VARCHAR(100),
	CEP CHAR(8) NOT NULL CHECK(LEN(CEP) = 8),
	PRIMARY KEY(ID_ENDERECO)
)
GO

/*CRIA TABELA PESSOA*/
CREATE TABLE PESSOA(
	ID_PESSOA INT IDENTITY NOT NULL,
	NOME VARCHAR(200) NOT NULL,
	CPF CHAR(11) UNIQUE NOT NULL CHECK(LEN(CPF) = 11),
	EMAIL VARCHAR(100) UNIQUE,
	DATA_NASCIMENTO DATETIME NOT NULL CHECK(DATA_NASCIMENTO < GETDATE()),
	FK_EDERECO_PESSOA INT NOT NULL,
	PRIMARY KEY(ID_PESSOA),
	FOREIGN KEY(FK_EDERECO_PESSOA) REFERENCES ENDERECO(ID_ENDERECO)
)
GO

/*CRIAR TABELA TELEFONE*/
CREATE TABLE TELEFONE(
	ID_TELEFONE INT IDENTITY NOT NULL,
	TIPO CHAR(3) NOT NULL,
	DDD CHAR(2) NOT NULL CHECK(LEN(DDD) = 2),
	TELEFONE CHAR(9) NOT NULL CHECK(LEN(TELEFONE) > 7),
	FK_PESSOA_TELEFONE INT NOT NULL,
	PRIMARY KEY(ID_TELEFONE),
	FOREIGN KEY(FK_PESSOA_TELEFONE) REFERENCES PESSOA(ID_PESSOA)
)
GO

/*CRIAR TABELA FUNCIONARIO*/
CREATE TABLE FUNCIONARIO(
	ID_FUNCIONARIO INT IDENTITY NOT NULL,
	CARGO VARCHAR(30) NOT NULL,
	MATRICULA VARCHAR(5) NOT NULL,
	DATA_ADMISSAO DATETIME NOT NULL,
	FK_PESSOA_fUNCIONARIO INT NOT NULL UNIQUE,
	PRIMARY KEY(ID_FUNCIONARIO),
	FOREIGN KEY(FK_PESSOA_FUNCIONARIO) REFERENCES PESSOA(ID_PESSOA)
)
GO

/*CRIAR TABELA USUARIO */
CREATE TABLE USUARIO(
	ID_USUARIO INT IDENTITY NOT NULL,
	LOGIN VARCHAR(15) UNIQUE NOT NULL,
	SENHA VARCHAR(30) NOT NULL,
	FK_FUNCIONARIO_USUARIO INT NOT NULL UNIQUE,
	PRIMARY KEY(ID_USUARIO),
	FOREIGN KEY(FK_FUNCIONARIO_USUARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
)
GO

/* CRIAR TABELA CLIENTE*/
CREATE TABLE CLIENTE(
	ID_CLIENTE INT IDENTITY NOT NULL,
	DATA_CADASTRO DATETIME NOT NULL,
	FK_PESSOA_CLIENTE INT NOT NULL UNIQUE,
	PRIMARY KEY(ID_CLIENTE),
	FOREIGN KEY(FK_PESSOA_CLIENTE) REFERENCES PESSOA(ID_PESSOA)
)
GO

/*CRIAR TABELA LIVRO*/
CREATE TABLE LIVRO(
	ID_LIVRO INT IDENTITY NOT NULL,
	TITULO VARCHAR(200) NOT NULL,
	ISBN VARCHAR(13) NOT NULL UNIQUE,
	GENERO VARCHAR(150) NOT NULL,
	EDICAO VARCHAR(3) NOT NULL,
	ANO CHAR(4) NOT NULL,
	PRECO_ATUAL DECIMAL (7,2) NOT NULL,
	QTS_ESTOQUE INT NOT NULL CHECK(QTS_ESTOQUE >= 0 ),
	IDIOMA VARCHAR(30) NOT NULL,
	DESCRICAO VARCHAR(MAX), 
	PRIMARY KEY(ID_LIVRO)
)
GO

/*CRIAR TABELA AUTOR*/
CREATE TABLE AUTOR(
	ID_AUTOR INT IDENTITY NOT NULL,
	NOME VARCHAR(150) NOT NULL UNIQUE,
	NACIONALIDADE VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID_AUTOR)
)
GO

/*CRIAR TABELA LIVRO/AUTOR*/
CREATE TABLE LIVRO_AUTOR(
	ID_LIVRO_AUTOR INT IDENTITY NOT NULL,
	FK_LIVRO_LIVRO_AUTOR INT NOT NULL,
	FK_AUTOR_LIVRO_AUTOR INT NOT NULL,
	PRIMARY KEY(ID_LIVRO_AUTOR),
	FOREIGN KEY(FK_LIVRO_LIVRO_AUTOR) REFERENCES LIVRO(ID_LIVRO),
	FOREIGN KEY(FK_AUTOR_LIVRO_AUTOR) REFERENCES AUTOR(ID_AUTOR),
)
GO

/*CRIAR TABELA PREÇO*/
CREATE TABLE PRECO(
	ID_PRECO INT IDENTITY NOT NULL,
	DATA_PRECO DATETIME,
	VALOR DECIMAL(6,2) NOT NULL CHECK(VALOR >= 0),
	FK_LIVRO_PRECO INT NOT NULL,
	PRIMARY KEY(ID_PRECO),
	FOREIGN KEY(FK_LIVRO_PRECO) REFERENCES LIVRO(ID_LIVRO)
)
GO

CREATE TABLE VENDA(
	ID_VENDA INT IDENTITY NOT NULL,
	DATA_VENDA DATETIME NOT NULL,
	FK_CLIENTE_VENDA INT NOT NULL,
	FK_LIVRO_VENDA INT NOT NULL,
	PRIMARY KEY(ID_VENDA),
	FOREIGN KEY(FK_CLIENTE_VENDA) REFERENCES CLIENTE(ID_CLIENTE),
	FOREIGN KEY(FK_LIVRO_VENDA) REFERENCES LIVRO(ID_LIVRO)
)

/* INSERIR  ENDEREÇO */
INSERT INTO ENDERECO VALUES
('ALAMEDA GOIAS', 250,'JD PAULISTA', 'SÃO PAULO', 'SP', 'AP 780', '01235952' ),
('ITAQUERA', 50,'JD FIM DO MUNDO', 'SÃO PAULO', 'SP', 'CJ 2', '51236521' )

/* INSERIR PESSOA */

INSERT INTO PESSOA VALUES
('JOAO DA SILVA', '12345678901','JOÃO@EMAIL.COM','05-16-1985', 1),
('ARISTEU', '13526352635','ARISTEU@EMAIL.COM','01-30-1980', 2)

/* INSERIR TELEFONE*/
INSERT INTO TELEFONE VALUES
('CEL', '11','985623522', 1),
('CEL', '11','951236542', 2)

/* INSERIR FUNCIONARIO */
INSERT INTO FUNCIONARIO VALUES
('GERENTE','1235','11-25-2015',1)

/*INSERIR USUARIO*/
INSERT INTO USUARIO VALUES
('JOAO', 'SENHAJOAO',1)

/*INSERIR CLIENTE */
INSERT INTO CLIENTE VALUES
('10-20-2020',2)

/* INSERIR LIVRO*/
INSERT INTO LIVRO VALUES
('MEU PRIMEIRO LIVRO','123','TERRO','1','2010',100,10,'ALEMÃO','PENSA EM UM LIVRO CHATO, É ESTE')

/* INSERER PREÇO */
INSERT INTO PRECO VALUES
(GETDATE(), 25.23,1)

/*INSERIR AUTOR*/
INSERT INTO AUTOR VALUES
('VERUSKS', 'ALEMÃO')

/*INSERIR LUVRO_AUTOR*/
INSERT INTO LIVRO_AUTOR VALUES
(1,1)

/*INSERIR UMA VENDA*/
INSERT INTO VENDA VALUES
(GETDATE(), 1,1)

/* SELECT PARA TESTAR*/
SELECT NOME, TITULO, DATA_VENDA
FROM PESSOA P, VENDA V, LIVRO L
WHERE P.ID_PESSOA = 1 AND V.FK_CLIENTE_VENDA =1 AND L.ID_LIVRO  = V.FK_LIVRO_VENDA
